# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghost" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "98f0b96f97cd0ec33c3ad00225035dd05816b2b1f8e77eb7a826b408627ef4bf"
      url "https://install.ghost.build/releases/v#{version}/ghost_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5db4266a2c77b7b5f9c0f9e9956bf1c1a4d21668ef254e67cc7ff27c21bad74b"
      url "https://install.ghost.build/releases/v#{version}/ghost_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "846f809d89fedca0f80b1ac72f99a0a89be7c458f0f7acaec22bf646cde39f66"
      url "https://install.ghost.build/releases/v#{version}/ghost_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2a456df40872cb797750d3b21a14c2ac3214fe078f3497d079e9bc1171dcab10"
      url "https://install.ghost.build/releases/v#{version}/ghost_Linux_arm64.tar.gz"
    end
  end

  name "ghost"
  desc "Ghost - The first database designed for agents.
Unlimited Postgres databases you can create, fork, and discard freely. Built for how agents actually work."
  homepage "https://ghost.build"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghost"
  bash_completion "completions/ghost.bash"
  fish_completion "completions/ghost.fish"
  zsh_completion "completions/ghost.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghost"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Ghost CLI has been installed successfully!\n\nGet started with:\n  ghost init\n  ghost create\n\nFor help:\n  ghost help
  EOS
end
