# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghost" do
  version "0.18.0"

  on_macos do
    on_intel do
      sha256 "95dd740dc59b55b811e157bb55e62584623442a13c01c6a734170483614304f2"
      url "https://install.ghost.build/releases/v#{version}/ghost_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "331b1e6a8e47439393de67f3a299921669996ee2e9465aaa44e66f98d46e10cd"
      url "https://install.ghost.build/releases/v#{version}/ghost_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5024c0c01334dd8bcf0477b63a7f262cb6a3d6298bcbce78894ea76a0e5c792a"
      url "https://install.ghost.build/releases/v#{version}/ghost_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a47497e3f13a6c73f32394a71132c174bbc63735f7d689734519241a0c19bbd0"
      url "https://install.ghost.build/releases/v#{version}/ghost_Linux_arm64.tar.gz"
    end
  end

  name "ghost"
  desc "Ghost - The first database designed for agents.
Unlimited Postgres databases you can create, fork, and discard freely. Built for how agents actually work."
  homepage "https://ghost.build"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghost"
  bash_completion "completions/ghost.bash"
  fish_completion "completions/ghost.fish"
  zsh_completion "completions/ghost.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghost"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Ghost CLI has been installed successfully!\n\nGet started with:\n  ghost init\n  ghost create\n\nFor help:\n  ghost help
  EOS
end
