# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghost" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "0741de8754c808374475561e930f908eea49897c34cdcb3895d9b9f7f72f4a16"
      url "https://install.ghost.build/releases/v#{version}/ghost_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c28c5790b3814700986b45757dab9517c99e4b6dc87932bc92d5a57e42c473e0"
      url "https://install.ghost.build/releases/v#{version}/ghost_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fcbbfcab7e8678d00d3b95e1c0ac7d1993d35be94227245a2ff6c0a05cd0ff84"
      url "https://install.ghost.build/releases/v#{version}/ghost_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f2cd5295f7333db8a072655b414884d5384dbe27c251de67b6d65646243aafa9"
      url "https://install.ghost.build/releases/v#{version}/ghost_Linux_arm64.tar.gz"
    end
  end

  name "ghost"
  desc "Ghost - The first database designed for agents.
Unlimited Postgres databases you can create, fork, and discard freely. Built for how agents actually work."
  homepage "https://ghost.build"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghost"
  bash_completion "completions/ghost.bash"
  fish_completion "completions/ghost.fish"
  zsh_completion "completions/ghost.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghost"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Ghost CLI has been installed successfully!\n\nGet started with:\n  ghost login\n  ghost mcp install\n\nFor help:\n  ghost help
  EOS
end
