# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiger-cli" do
  name "tiger-cli"
  desc "Tiger CLI - TigerData Cloud Platform CLI
Command-line interface for managing TigerData Cloud Platform resources"
  homepage "https://github.com/timescale/tiger-cli"
  version "0.9.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiger"

  on_macos do
    on_intel do
      url "https://cli.tigerdata.com/releases/v#{version}/tiger-cli_Darwin_x86_64.tar.gz"
      sha256 "7f4890124eff2f96815afd0554fba67e11a1731b2d676ac2ec1c29d82b4107f6"
    end
    on_arm do
      url "https://cli.tigerdata.com/releases/v#{version}/tiger-cli_Darwin_arm64.tar.gz"
      sha256 "3cc04850e1df7e009b0c5fc52ad50620d68930852d88785f1ddee06214b0c981"
    end
  end

  on_linux do
    on_intel do
      url "https://cli.tigerdata.com/releases/v#{version}/tiger-cli_Linux_x86_64.tar.gz"
      sha256 "b36acf752f416aa83259045521a04356a8c9e8d55d9f71a81677da5865e8f54c"
    end
    on_arm do
      url "https://cli.tigerdata.com/releases/v#{version}/tiger-cli_Linux_arm64.tar.gz"
      sha256 "41268bff8c14c51919e32505c6f90d53fb6f22570b410f778019d0c1efe3873b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiger"]
    end
  end

  caveats do
    "Tiger CLI has been installed successfully!"
    ""
    "Get started with:"
    "  tiger auth login"
    ""
    "For help:"
    "  tiger --help"
  end

  # No zap stanza required
end
