# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiger-cli" do
  name "tiger-cli"
  desc "Tiger CLI - TigerData Cloud Platform CLI
Command-line interface for managing TigerData Cloud Platform resources"
  homepage "https://github.com/timescale/tiger-cli"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiger"

  on_macos do
    on_intel do
      url "https://tiger-cli-releases.s3.us-east-1.amazonaws.com/releases/v#{version}/tiger-cli_Darwin_x86_64.tar.gz"
      sha256 "b3e4aea0036402c57d16f1c0a1cc7420453b994f2d08a3b57e786ced1d6ebc9b"
    end
    on_arm do
      url "https://tiger-cli-releases.s3.us-east-1.amazonaws.com/releases/v#{version}/tiger-cli_Darwin_arm64.tar.gz"
      sha256 "93840ebe42f5f4abc0ed161844ef0b94bfeeb5f3c5e49244f84b17a9bd2fc002"
    end
  end

  on_linux do
    on_intel do
      url "https://tiger-cli-releases.s3.us-east-1.amazonaws.com/releases/v#{version}/tiger-cli_Linux_x86_64.tar.gz"
      sha256 "b4a5a86ba9b3550027c7303311b78904763c75ed322f386c8b38ca7235217726"
    end
    on_arm do
      url "https://tiger-cli-releases.s3.us-east-1.amazonaws.com/releases/v#{version}/tiger-cli_Linux_arm64.tar.gz"
      sha256 "12d29dabb8974c940ee26b9dc6cc7fd3736e74e914cd466d35543360df18db63"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiger"]
    end
  end

  caveats do
    "Tiger CLI has been installed successfully!"
    ""
    "Get started with:"
    "  tiger auth login"
    ""
    "For help:"
    "  tiger --help"
  end

  # No zap stanza required
end
