# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiger-cli" do
  name "tiger-cli"
  desc "Tiger CLI - TigerData Cloud Platform CLI
Command-line interface for managing TigerData Cloud Platform resources"
  homepage "https://github.com/timescale/tiger-cli"
  version "0.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiger"

  on_macos do
    on_intel do
      url "https://cli.tigerdata.com/releases/v#{version}/tiger-cli_Darwin_x86_64.tar.gz"
      sha256 "de7fe65472bc4034a8b8de0f11a1246341edea889eb25387924f3b61920ce1f1"
    end
    on_arm do
      url "https://cli.tigerdata.com/releases/v#{version}/tiger-cli_Darwin_arm64.tar.gz"
      sha256 "3e53d68cd7e1f6a204481a19b82230e4223fb3dabf78f220ff7d6c7883c64779"
    end
  end

  on_linux do
    on_intel do
      url "https://cli.tigerdata.com/releases/v#{version}/tiger-cli_Linux_x86_64.tar.gz"
      sha256 "b97c1ddc3fc49169f63326167f808a2b23b7952196fbb34c744440613b12ea19"
    end
    on_arm do
      url "https://cli.tigerdata.com/releases/v#{version}/tiger-cli_Linux_arm64.tar.gz"
      sha256 "526086680f3d97ac8d8a43a63d55192ea6579a4c0ef191988a2f0fa64358228e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiger"]
    end
  end

  caveats do
    "Tiger CLI has been installed successfully!"
    ""
    "Get started with:"
    "  tiger auth login"
    ""
    "For help:"
    "  tiger --help"
  end

  # No zap stanza required
end
